Repository walletpass/pass-js, pull requests merged in 2019-05, with the labels that each got.

#62 load localizations and constitently rename images methods
  README.md
  __tests__/__snapshots__/localizations.ts.snap
  __tests__/images.ts
  __tests__/localizations.ts
  __tests__/pass.ts
  package-lock.json
  package.json
  src/lib/base-pass.ts
  src/lib/images.ts
  src/lib/localizations.ts
  src/pass.ts
  src/template.ts
Labels: bug, enhancement

#63 6.2
  README.md
  __tests__/__snapshots__/pass.ts.snap
  __tests__/images.ts
  __tests__/pass.ts
  __tests__/template.ts
  package-lock.json
  package.json
  src/constants.ts
  src/interfaces.ts
  src/lib/base-pass.ts
  src/lib/fieldsMap.ts
  src/lib/get-geo-point.ts
  src/lib/images.ts
  src/lib/nfc-fields.ts
  src/lib/pass-color.ts
  src/lib/pass-structure.ts
  src/pass.ts
  src/template.ts
Labels: enhancement

#64 remove `nfc.addRaw`
  __tests__/nfc-field.ts
  azure-pipelines.yml
  src/lib/nfc-fields.ts
  src/lib/pass-structure.ts
Labels: bug

#65 6.2.1
  package-lock.json
  package.json
  src/constants.ts
  src/interfaces.ts
  src/lib/fieldsMap.ts
Labels: enhancement

#70 remove fast-glob
  README.md
  __tests__/__snapshots__/images.ts.snap
  __tests__/images.ts
  package-lock.json
  package.json
  src/lib/images.ts
  src/lib/localizations.ts
  src/template.ts
Labels: dependencies

#73 implement `Template.fromBuffer`
  .eslintrc
  .npmrc
  README.md
  __tests__/base-pass.ts
  __tests__/images.ts
  __tests__/normalize-locale.ts
  __tests__/resources/passes/Generic.zip
  __tests__/template.ts
  jest.config.js
  package-lock.json
  package.json
  src/lib/images.ts
  src/lib/localizations.ts
  src/lib/normalize-locale.ts
  src/lib/pass-color.ts
  src/lib/stream-to-buffer.ts
  src/pass.ts
  src/template.ts
Labels: bug, dependencies, new feature

#84 make pass.json from Buffer instead of string, for non english text
  package-lock.json
  package.json
  src/pass.ts
Labels: bug, dependencies
